import "bootstrap/dist/css/bootstrap.min.css";
import "@mantine/core/styles.css";
import '@mantine/notifications/styles.css';
import "@mantine/dates/styles.css";
import "yet-another-react-lightbox/styles.css";
import BootstrapClient from "@/components/BootstrapClient";
import ScrollTop from "@/components/ScrollTop/ScrollTop";
import "./globals.css";
import "./mediaquery.css";
import "swiper/css";
import LayoutVisibility from "@/components/LayoutVisibility";
import { MantineProvider } from "@mantine/core";
import { CurrencyProvider } from "@/util/currency";
import { Notifications } from '@mantine/notifications';
import NextTopLoader from "nextjs-toploader";
export const metadata = {
  title: "Kashta",
  description: "Generated by create next app",
  icons: {
    icon: "/public/tick.svg"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="scrool">
        <CurrencyProvider>
          <BootstrapClient />
          <MantineProvider>
            <NextTopLoader height={3} crawl={true} showSpinner={false}/>
            <Notifications position="top-right" />
            <LayoutVisibility>{children}</LayoutVisibility>
          </MantineProvider>
        </CurrencyProvider>
        <ScrollTop />
           
      </body>
    </html>
  );
}
